### ISSUE TITLE
Migrate to Go modules

### ISSUE THREAD

**Issue by mraerino** [testcontainers/testcontainer-go#18]
Since Go 1.11 we have an official way of supplying dependencies and their versions to the go tooling: Via `go.mod` and `go.sum`.

It should be easy to migrate from Gopkg to Go mod.

Do you want to go forward with that? I could probably submit a PR.

**Comment by gianarb** [comment]
Hello! I don't really have a strict opinion, I think you can just run `go mod init` and push the result, we can keep both `Gopkg` and `go.mod` for now.

**Comment by gianarb** [comment]
Looking around I think is better to just keep only vgo.
