### ISSUE TITLE
Allow manual start of container

### ISSUE THREAD

**Issue by mraerino** [testcontainers/testcontainer-go#20]
The java implementation actually requires users of the library to start the container on their own or use a test framework integration.

The go lib should probably also provide a way to start the container on request rather than on creation of the testcontainer setup.

**Comment by gianarb** [comment]
We can build a function similar to `RunContrainer` https://github.com/testcontainers/testcontainer-go/blob/master/docker.go#L109` but called `CreateContainer` adding a function `Run()` to the container. The function is executable only one time I suppose. You can not run a Container twice.
