### ISSUE TITLE
Test library via TravisCI

### ISSUE THREAD

**Issue by mraerino** [testcontainers/testcontainer-go#23]
I've seen that there is a PR (#12) by @gianarb on integrating a CircleCI config.

I'd like to propose integrating TravisCI since they are able to run docker inside the VM the test runs in.
Also, most open-source projects currently use Travis.

What CI would you rather like to support?

**Comment by gianarb** [comment]
Just one is fine, I picked circleci because I think it is what the other projects like the java implementation uses. But I don't have a blocking one :) The best we can get in place is good

**Comment by gianarb** [comment]
I think we can keep trying to make circleci to work @mraerino I don't think we need travis for now
