### ISSUE TITLE
Re-work exposed ip and mapped port

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainer-go#31]
@rnorth I think I need to understand what's the easier approach to re-implement the "most-compatible" `GetContainerAddress`  and `GetMappedPort` function. Right now I think I did it in a wrong way.

The get address returns the ip of the container and we have a function that returns the binding port in the host for a port. But as you can see this doesn't work.

Do you have some feedback about the easier fix that I can do to have something that can work?

**Comment by gianarb** [comment]
This is how I think it should be: https://github.com/testcontainers/testcontainer-go/pull/34

**Comment by mraerino** [comment]
Addressed in #35 and implemented in #36

**Comment by gianarb** [comment]
https://github.com/testcontainers/testcontainer-go/pull/36

**Comment by gianarb** [comment]
Thanks a lot @mraerino !
