### ISSUE TITLE
Current wait strategy are weird.

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainer-go#33]
Hello @MeneDev I looked again at the WaitStrategy we have right now, but I don't think they have a lot of sense. I think we should rewrite them to wait on a single port, and probably the waitingFor parameter should be an array of waiting strategies. What do you think?

**Comment by gianarb** [comment]
This is what I think should be for now:
https://github.com/testcontainers/testcontainer-go/pull/34

**Comment by mraerino** [comment]
This is addressed in my PR: #36
