### ISSUE TITLE
Testcontainers project

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainer-go#6]
Hi!

I'm a member of the Testcontainers project and happy to see that you're working on a Golang version.

We already have some ports in works (like .NET or Python). Do you maybe want to join the organization and continue the development as a part of it?
It will also save you a lot of time answering questions like "is your Golang implementation the official one" :D

From our side we have a lot of experience to share, and we were also planning to cover more languages (including Golang), so I think the collaboration would help both sides 👍 

What do you think? :)

**Comment by gianarb** [comment]
:tada:
